-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO role (slug, name, description)
-- VALUES
--     ('Importer', 'Importer', 'Voucher importer user.'),
--     ('DE', 'DE', 'Data encoder user.');
