-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."setting" add column "to_ind_agents" numeric
--  null default '0';
