-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."distributor" add column "max_print" integer
--  not null default '500';
