-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO role (slug, name, description)
-- VALUES
--     ('Auditor', 'Auditor', 'Deposit auditor user.');
