-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."batch_sale" add column "corrected" boolean
--  not null default 'false';
